### ISSUE TITLE
Unable to Install Client - Retry

### ISSUE THREAD

**Issue by dakoellis** [realm01/DHCPv6-Client-Android#12]
hey @realmar I know you aren't actively maintaining this project anymore, but I was hoping you could help me out with this issue really quickly.  Is there a folder dir I can drop the files in manually to get this app working?  I'm on an Essential PH-1 Running Oreo with A/B if that matters

**Comment by realmar** [comment]
Hey @dakoellis the app will install following files in following directories: (Source: https://github.com/realmar/DHCPv6-Client-Android/blob/master/app/src/main/java/org/daduke/realmar/dhcpv6client/DHCPv6Integrity.java)

```
/system/bin/dhcp6c
/system/etc/wide-dhcpv6/dhcp6c.script
/system/etc/wide-dhcpv6/dhcp6cctlkey
/system/bin/dhcp6ctl
/system/etc/wide-dhcpv6/dhcp6c.conf
/system/etc/wide-dhcpv6/dhcp6cDNS.conf
```

This means that you would need to create following directory: `/system/etc/wide-dhcpv6`.

If you want to write to those locations, you need to remount `/system` read-write: `mount -o rw,remount /system`.

Hope that helps, if you have any further questions, feel free to ask.
