### ISSUE TITLE
Missing http://realmar.daduke.org/dhcp/dhcpv6_base.zip

### ISSUE THREAD

**Issue by dl12345** [realm01/DHCPv6-Client-Android#2]
This and  http://realmar.daduke.org/dhcp/dhcpv6_update.zip are giving 404 not found errors. Any chance of making them available somewhere else?

**Comment by realmar** [comment]
Thank you for your issue. I will make those files as soon as possible available again.

**Comment by realmar** [comment]
Updated URLs in 9e760111a33addeaffe4a0720657a270179d8ac5 (realmar.daduke.org -> cmmn.realmar.net)

Closing Issue now.
