### ISSUE TITLE
This app doesn't work until I adb shell into my device and run dhcp6c wlan0 as root manually

### ISSUE THREAD

**Issue by Mygod** [realm01/DHCPv6-Client-Android#3]

**Comment by Mygod** [comment]
Okay after a while of debugging it seems `ps | grep dhcp6c` returns `grep dhcp6c` as a result on my device.

**Comment by Mygod** [comment]
Now on dhcp6ctl, it shows this: `client6_ifctl: failed to find interface configuration for wlan0`

**Comment by realmar** [comment]
Thank you for your pull request! I will now create a signed build for the google play store.
